### ISSUE TITLE
Camera can not be open!

### ISSUE THREAD

**Issue by talhacomak** [saki4510t/OpenCVwithUVC#39]
When i select and allow the camera, getting the error below.

```
2022-10-12 12:42:12.462 4810-4848/? E/AndroidRuntime: FATAL EXCEPTION: CameraThread
    Process: com.serenegiant.opencvwithuvc, PID: 4810
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.serenegiant.opencvwithuvc-oJBPfmMLvQzFVaP7G99HYQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.serenegiant.opencvwithuvc-oJBPfmMLvQzFVaP7G99HYQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libjpeg-turbo1500.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.serenegiant.usb.UVCCamera.<clinit>(UVCCamera.java:119)
        at com.serenegiant.usbcameracommon.AbstractUVCCameraHandler$CameraThread.handleOpen(AbstractUVCCameraHandler.java:443)
        at com.serenegiant.usbcameracommon.AbstractUVCCameraHandler.handleMessage(AbstractUVCCameraHandler.java:300)
        at com.serenegiant.usbcameracommon.UVCCameraHandlerMultiSurface.handleMessage(UVCCameraHandlerMultiSurface.java:33)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at com.serenegiant.usbcameracommon.AbstractUVCCameraHandler$CameraThread.run(AbstractUVCCameraHandler.java:747)

```
in an Android 10 smartphone.

**Comment by juice77ooO** [comment]
Did you solved the error? I have the seem.
